### ISSUE TITLE
Assistance VisualRegression configuration 

### ISSUE THREAD

**Issue by greaveselliott** [theintern/intern-visual#13]
Hi,

I'm having some trouble configuring the VisualRegression reporter. Following the documentation, I have installed this package then have included the following in my Intern configuration file.

`
...
	reporters: [
		'runner',
		'intern-visual/reporters/VisualRegression'
	],
...
`

When running the tests I receive the following error.

`
Error: Failed to load module visual/reporters/VisualRegression from /xxx/xxx/xxx/intern-test/node_modules/intern-visual/reporters/VisualRegression.js (parent: *26)
  at ReadFileContext.callback  <node_modules/dojo/loader.ts:831:119>
  at FSReqWrap.readFileAfterOpen [as oncomplete]  <fs.js:406:13>
`

**Comment by greaveselliott** [comment]
I've solved my configuring issue by by referencing @rozaev repo https://github.com/rozaev/intern-visual-demo/tree/how-to-make-screenshot-for-entire-page

**Comment by rozaev** [comment]
@greaveselliott you should know that it project is not production-ready code at all and seems that Intern team are not going to support it right now.

If you need some visual regression tool, use gemini (https://github.com/gemini-testing/gemini) or something else.

**Comment by jason0x43** [comment]
Sorry for not responding to this sooner; we missed the issue notification. In any case, this project definitely needs some love (it still hasn't been updated to properly support Intern 4, for one), we just haven't had much time to spend on it lately. It's definitely on the road map, though.

**Comment by greaveselliott** [comment]
Thanks for your comments @vrozaev and @jason0x43. I'll look into Gemini for the time being, quite keen to see how this tool develops.
