### ISSUE TITLE
Need new release for fix build

### ISSUE THREAD

**Issue by rozaev** [theintern/intern-visual#6]
Hello! I can't complete my intern-visual demo example because this commit:
https://github.com/theintern/intern-visual/commit/b4f251dbc0251b0d247428bd166f143cfd236cbb

Didn't included in current intern-visual version (0.1.1). So, right now intern-visual didn't work! Please, update intern-visual up to 0.1.2 and then I finish my little demo app and merge it to intern examples.

**Comment by rozaev** [comment]
@dylans  @jason0x43 Any progress with this request?

Is this project has no priorite?)

**Comment by dylans** [comment]
@rozaev I'm sorry, I mistakenly thought that @devpaul had done this already a few weeks ago... will ping him this morning.

**Comment by devpaul** [comment]
I thought I did this as well! I cleaned up the release a bit and published 0.1.2.
